services:
  - type: web
    name: eventcheck
    runtime: python
    plan: free
    buildCommand: |
      apt-get update -y
      apt-get install -y tesseract-ocr tesseract-ocr-fra
      pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: ma_cle_secrete_2024
      - key: ADMIN_PASSWORD
        value: eventcheck2024
      - key: DATABASE_URL
        fromDatabase:
          name: eventcheck-db
          property: connectionString

databases:
  - name: eventcheck-db
    plan: free