services:
  - type: web
    name: eventcheck
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: ma_cle_secrete_2024
      - key: ADMIN_PASSWORD
        value: eventcheck2024
    disk:
      name: eventcheck-data
      mountPath: /app/data
      sizeGB: 1